CREATE DATABASE CountryAppDB
USE CountryAppDB
CREATE TABLE Countries(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR NOT NULL UNIQUE,
	Area DECIMAL(20,2) NOT NULL
)
CREATE TABLE Cities(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR NOT NULL,
	Area DECIMAL(20,2) NOT NULL,
	CountryId INT FOREIGN KEY REFERENCES Countries(Id)
)

SELECT * FROM Countries
SELECT * FROM Cities